### ISSUE TITLE
Too Handsome

### ISSUE THREAD

**Issue by willlogs** [alirezaft/UnityVerletRope#1]
I have an issue with how handsome the maintainer of this repo is.
Please respond.

**Comment by alirezaft** [comment]
Hi, thanks for reaching out about this issue. Unfortunately, a downgrade of the project is not possible. A possible solution can be adding a mirror to your room and looking at yourself and seeing how handsome you are, maybe even more than the maintainer of this repo. I hope this helps resolve the issue.
